

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "test",
    "password": "test",
    "email": "test@example.com",
    "profilePicture": "default.jpg",
    "bio": "This is a test user"
}

